---
deployment:
  tasks:
    - export COMPOSER_ALLOW_SUPERUSER=1
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --no-interaction
    - chmod -R 775 storage bootstrap/cache
